web-dev:
  dockerfile: Dockerfile.dev
  build: .
  working_dir: /src/app
  command: npm run dev
  volumes:
    - ".:/src/app"
  ports:
    - "8000:8000"
    - "5858:5858"
  links:
    - "session:redis"
    - "db:mongo"

session:
  image: redis
  ports:
    - "6379:6379"

db:
  image: mongo
  ports:
    - "27017:27017"
